### PR TITLE
Add note about changing the command executed when hitting return

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
@georgebrock @mike-burns Thoughts on this simple addition to the README?

**Comment by mike-burns** [comment]
I'm OK with this addition. Some syntax thoughts: wrap at 80 columns, put a semicolon before "remember".

**Comment by jakirkham** [comment]
> I'm OK with this addition. Some syntax thoughts: wrap at 80 columns, put a semicolon before "remember".

Thanks for the feedback. Changed.

**Comment by georgebrock** [comment]
Looks good to me. Thanks @jakirkham

**Comment by georgebrock** [comment]
Merged as 676207d6436c0110525f2630e74718a05479bbe6

**Pull request closed without merging**
